version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=your_strong_password
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./oracle-data:/opt/oracle/oradata
    networks:
      - app-network

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

